"use client";

import { useMemo, useState, useTransition } from "react";
import { addCcaCapture, removeCcaCapture } from "./actions";
import { ccaActiveOn, ccaActivities, ccaDayFor, ccaSeasonFor, type CcaActivity } from "../lib/cca-data";

export type CcaCapture = { id: string; activity_id: string; capture_date: string; created_at: string };
const target = 2;
const today = new Date().toISOString().slice(0, 10);

function countFor(activity: CcaActivity, captures: CcaCapture[]) { return captures.filter((capture) => capture.activity_id === activity.id && capture.capture_date >= activity.startDate && capture.capture_date <= activity.endDate).length; }
function timeFor(activity: CcaActivity, date: string) { return date === activity.startDate || new Date(`${date}T12:00:00`).getHours() < 12 ? activity.morningTime : activity.afternoonTime; }

export function CcaTodaySummary({ date, captures, onOpen }: { date: string; captures: CcaCapture[]; onOpen: () => void }) {
  const activities = ccaActivities.filter((activity) => ccaActiveOn(activity, date));
  if (!activities.length) return null;
  return <section className="panel cca-summary"><div className="panel-header"><div><strong>Athletics and CCA today</strong><div className="muted">{ccaDayFor(date)} · {activities.length} scheduled activities</div></div><button className="secondary" onClick={onOpen}>View all activities</button></div>{activities.map((activity) => <div className="cca-summary-row" key={activity.id}><div><strong>{activity.name}</strong><div className="class-meta">{activity.space} · {activity.coaches}</div></div><span className="photo-count">{countFor(activity, captures)}/{target}</span></div>)}</section>;
}

export default function CcaDashboard({ date: initialDate, initialCaptures, onCapturesChange }: { date: string; initialCaptures: CcaCapture[]; onCapturesChange: (captures: CcaCapture[]) => void }) {
  const [date, setDate] = useState(initialDate || today); const [season, setSeason] = useState(ccaSeasonFor(initialDate || today) || "Season 1"); const [day, setDay] = useState("all"); const [category, setCategory] = useState("all"); const [query, setQuery] = useState(""); const [captures, setCaptures] = useState(initialCaptures); const [pending, startTransition] = useTransition();
  const activities = useMemo(() => ccaActivities.filter((activity) => activity.season === season && (!query || `${activity.name} ${activity.coaches} ${activity.space}`.toLowerCase().includes(query.toLowerCase())) && (day === "all" || activity.days.includes(day)) && (category === "all" || activity.category === category)), [season, query, day, category]);
  function update(next: CcaCapture[]) { setCaptures(next); onCapturesChange(next); }
  function add(activity: CcaActivity) { if (!ccaActiveOn(activity, date) || captures.some((capture) => capture.activity_id === activity.id && capture.capture_date === date)) return; startTransition(async () => { const result = await addCcaCapture(activity.id, date); if (result.capture) update([...captures, result.capture as CcaCapture]); else if (result.error) window.alert(result.error); }); }
  function remove(activity: CcaActivity) { const match = captures.find((capture) => capture.activity_id === activity.id && capture.capture_date === date); if (!match) return; if (!window.confirm(`Remove today's visit for ${activity.name}?`)) return; startTransition(async () => { const result = await removeCcaCapture(match.id); if (result.ok) update(captures.filter((capture) => capture.id !== match.id)); else if (result.error) window.alert(result.error); }); }
  const reached = activities.filter((activity) => countFor(activity, captures) >= target).length;
  return <><div className="eyebrow">Live activities</div><div className="heading-row"><div><h1>Athletics and CCA</h1><p>Where to go, when to go, and what still needs coverage.</p></div><div className="controls"><label>Visit date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Season<select value={season} onChange={(event) => setSeason(event.target.value as typeof season)}><option>Season 1</option><option>Season 2</option><option>Season 3</option></select></label></div></div><div className="filter-grid cca-filters"><input placeholder="Search activity, coach, or location..." value={query} onChange={(event) => setQuery(event.target.value)} /><select value={day} onChange={(event) => setDay(event.target.value)}><option value="all">All days</option>{["Monday", "Tuesday", "Friday"].map((value) => <option key={value}>{value}</option>)}</select><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option><option>Athletics</option><option>Activities</option></select></div><div className="metrics"><div><span>Activities shown</span><strong>{activities.length}</strong></div><div><span>Target reached</span><strong>{reached}</strong></div><div><span>Visits logged</span><strong>{activities.reduce((sum, activity) => sum + countFor(activity, captures), 0)}</strong></div><div><span>Target</span><strong>2 / season</strong></div></div><div className="panel"><div className="panel-header"><div><strong>{day === "all" ? "All season activities" : `${day} activities`}</strong><div className="muted">{season} · {date} · {activities.length} shown</div></div></div>{activities.map((activity) => { const count = countFor(activity, captures); const countedToday = captures.some((capture) => capture.activity_id === activity.id && capture.capture_date === date); const scheduledToday = ccaActiveOn(activity, date); return <div className="cca-row" key={activity.id}><div className="cca-activity-main"><div className="cca-activity-title"><strong>{activity.name}</strong><span className="cca-category">{activity.category}</span>{activity.reviewNote && <span className="cca-review">Needs review</span>}</div><div className="class-meta">{activity.days.join(" · ")} · {timeFor(activity, date)} · <b>{activity.space}</b> · {activity.coaches}</div>{activity.reviewNote && <div className="cca-review-note">{activity.reviewNote}</div>}<div className="cca-progress"><i style={{ width: `${Math.min(count / target, 1) * 100}%` }} /></div></div><div className="cca-controls"><span className="photo-count">{count}/{target}</span><button className="cca-step" aria-label={`Remove visit for ${activity.name}`} disabled={!countedToday || pending} onClick={() => remove(activity)}>−</button><button className="cca-step" aria-label={`Log visit for ${activity.name}`} disabled={!scheduledToday || countedToday || pending} onClick={() => add(activity)}>+</button></div></div>; })}</div></>;
}
