"use client";

import { useMemo, useState, useTransition } from "react";
import { addCapture, removeCapture } from "./actions";
import { scheduleData } from "../lib/schedule-data";

type Capture = { id: string; class_id: string; capture_date: string; created_at: string };
type ClassItem = (typeof scheduleData.classes)[number];
const target = 10;
const periods = scheduleData.periods;
const today = new Date().toISOString().slice(0, 10);

function numbers(item: ClassItem) { const text = `${item.gradeContext || ""} ${item.subject || ""}`; const found = [...text.matchAll(/(?:Grades?|G)\s*(6|7|8|9|10|11|12)(?:\s*[-/]\s*(6|7|8|9|10|11|12))?/gi)].flatMap((m) => [m[1], m[2]]).filter(Boolean).map(Number); return [...new Set(found)].sort((a, b) => a - b); }
function gradeLabel(item: ClassItem) { const ns = numbers(item); return ns.length > 1 ? `Grades ${ns.join("-")}` : ns.length ? `Grade ${ns[0]}` : "Unassigned"; }
function schoolBand(item: ClassItem) { const ns = numbers(item); return ns.length && ns.every((n) => n <= 8) ? "Middle School" : ns.length && ns.every((n) => n >= 9) ? "High School" : "Unassigned"; }
function rotationFor(date: string) { return scheduleData.rotations.find((r) => r.date === date); }
function periodFor(date: string, block: string) { const r = rotationFor(date); const index = (r?.blocks as readonly string[] | undefined)?.indexOf(block) ?? -1; return index >= 0 ? periods[index] : null; }
function shuffle<T>(items: T[]) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }

export default function Dashboard({ initialCaptures }: { initialCaptures: Capture[] }) {
  const [view, setView] = useState("today"); const [date, setDate] = useState<string>(rotationFor(today)?.date || scheduleData.rotations[0].date); const [grade, setGrade] = useState("all"); const [period, setPeriod] = useState("all"); const [captures, setCaptures] = useState(initialCaptures); const [pending, startTransition] = useTransition();
  const [randomMode, setRandomMode] = useState(false); const [randomCount, setRandomCount] = useState(4); const [randomBlock, setRandomBlock] = useState("all"); const [randomSelection, setRandomSelection] = useState<string[]>([]);
  const [query, setQuery] = useState(""); const [school, setSchool] = useState("all"); const [subject, setSubject] = useState("all"); const [teacher, setTeacher] = useState("all"); const [includeSupport, setIncludeSupport] = useState(false);
  const rotation = rotationFor(date);
  const countFor = (id: string) => captures.filter((c) => c.class_id === id && c.capture_date >= new Date(new Date().setMonth(new Date().getMonth() - 6)).toISOString().slice(0, 10) && c.capture_date <= today).length;
  const counted = (id: string) => captures.some((c) => c.class_id === id && c.capture_date === date);
  const classesForDate = (d: string) => { const r = rotationFor(d); const blocks = r?.blocks as readonly string[] | undefined; return scheduleData.classes.filter((c) => c.trackable && blocks?.includes(c.block)).sort((a, b) => (blocks?.indexOf(a.block) ?? 0) - (blocks?.indexOf(b.block) ?? 0) || a.subject.localeCompare(b.subject)); };
  const filteredToday = classesForDate(date).filter((c) => (grade === "all" || numbers(c).includes(Number(grade))) && (period === "all" || periodFor(date, c.block)?.number === Number(period)));
  const recentCaptureCount = captures.length;
  function mark(id: string) { startTransition(async () => { const result = await addCapture(id, date); if (result.capture) setCaptures((old) => [...old, result.capture as Capture]); }); }
  function remove(id: string) { startTransition(async () => { const result = await removeCapture(id); if (result.ok) setCaptures((old) => old.filter((c) => c.id !== id)); }); }
  function classRow(item: ClassItem) { const count = countFor(item.id); const done = counted(item.id); return <div className="class-row" key={item.id}><div className={`status-bar ${count >= target ? "complete" : count ? "review" : "pending"}`} /><div className="class-main"><strong>{item.subject}</strong><div className="class-meta">{item.gradeContext || "Grade not specified"} · {item.teacher || "Teacher not specified"} · {periodFor(date, item.block)?.label || "Unscheduled"} · Block {item.block}{item.room ? ` · ${item.room}` : ""}</div></div><div className="class-actions"><span className="photo-count">{count}/{target}</span><button disabled={done || pending} onClick={() => mark(item.id)}>{done ? "Counted today" : "Add capture"}</button></div></div>; }
  function randomPanel() { const candidates = filteredToday.filter((c) => !counted(c.id) && (randomBlock === "all" || periodFor(date, c.block)?.number === Number(randomBlock))); const chosen = scheduleData.classes.filter((c) => randomSelection.includes(c.id)); return <section className="panel random-panel"><div className="panel-header"><div><strong>Random Run</strong><div className="muted">Choose a block and roll an uncounted route.</div></div><label><input type="checkbox" checked={randomMode} onChange={(e) => { setRandomMode(e.target.checked); setRandomSelection([]); }} /> Random mode</label></div><div className="controls"><label>Block<select value={randomBlock} onChange={(e) => { setRandomBlock(e.target.value); setRandomSelection([]); }}><option value="all">All blocks today</option>{rotation?.blocks.map((b, i) => <option key={b} value={String(i + 1)}>P{i + 1} · Block {b}</option>)}</select></label><label>Classes<select value={randomCount} onChange={(e) => { setRandomCount(Number(e.target.value)); setRandomSelection([]); }}><option value={4}>4 classes</option><option value={6}>6 classes</option></select></label><button onClick={() => setRandomSelection(shuffle(candidates).slice(0, randomCount).map((c) => c.id))}>Roll the dice</button><button className="secondary" onClick={() => setRandomSelection([])}>Clear</button></div>{randomSelection.length > 0 && <div><div className="result-heading"><strong>Randomized route</strong><span>{chosen.length} selected · {candidates.length} available</span></div>{chosen.map(classRow)}</div>}</section>; }
  function todayView() { const done = filteredToday.filter((c) => countFor(c.id) >= target).length; const percent = filteredToday.length ? Math.round(filteredToday.reduce((n, c) => n + Math.min(countFor(c.id) / target, 1), 0) / filteredToday.length * 100) : 0; return <><div className="heading-row"><div><div className="eyebrow">Daily coverage</div><h1>Keep the day in frame.</h1><p>Four teaching periods count. Advisory and the break remain separate.</p></div><div className="controls"><label>Date<input type="date" value={date} onChange={(e) => { setDate(e.target.value); setRandomSelection([]); }} /></label><label>Grade<select value={grade} onChange={(e) => { setGrade(e.target.value); setRandomSelection([]); }}><option value="all">All grades</option>{[6,7,8,9,10,11,12].map((n) => <option key={n} value={n}>Grade {n}</option>)}</select></label></div></div>{randomPanel()}<div className="schedule-rule panel"><div><strong>{rotation?.label || "No rotation scheduled"}</strong><div className="muted">{date}</div></div><div className="chips">{rotation?.blocks.map((b, i) => <button className={period === String(i + 1) ? "selected" : ""} key={b} onClick={() => setPeriod(period === String(i + 1) ? "all" : String(i + 1))}>P{i + 1} · Block {b}</button>)}</div></div><div className="metrics"><div><span>Scheduled classes</span><strong>{filteredToday.length}</strong></div><div><span>Complete</span><strong>{done}</strong></div><div><span>Coverage</span><strong>{percent}%</strong></div><div><span>Saved captures</span><strong>{recentCaptureCount}</strong></div></div>{!randomMode && <div className="panel"><div className="panel-header"><strong>Teaching periods</strong><span className="muted">{target} capture days in six months</span></div>{periods.map((p) => { const rows = filteredToday.filter((c) => periodFor(date, c.block)?.number === p.number); return rows.length ? <section className="period-section" key={p.number}><div className="period-heading"><strong>Period {p.number}</strong><span>Block {rotation?.blocks[p.number - 1]} · {p.label}</span></div>{rows.map(classRow)}</section> : null; })}</div>}</>; }
  function dashboardView() { const list = classesForDate(date); const done = list.filter((c) => countFor(c.id) >= target).length; return <><div className="eyebrow">Live dashboard</div><h1>Know what is left.</h1><p>Coverage for {date}. Advisory stays separate.</p><div className="metrics"><div><span>Coverage</span><strong>{list.length ? Math.round(list.reduce((n, c) => n + Math.min(countFor(c.id) / target, 1), 0) / list.length * 100) : 0}%</strong></div><div><span>Complete</span><strong>{done}</strong></div><div><span>In progress</span><strong>{list.filter((c) => countFor(c.id) > 0 && countFor(c.id) < target).length}</strong></div><div><span>No captures</span><strong>{list.filter((c) => countFor(c.id) === 0).length}</strong></div></div><div className="panel"><div className="panel-header"><strong>Classes below target</strong><span className="muted">{list.filter((c) => countFor(c.id) < target).length}</span></div>{list.filter((c) => countFor(c.id) < target).slice(0, 12).map(classRow)}</div></>; }
  function classesView() { const grades = [...new Set(scheduleData.classes.map(gradeLabel))].sort(); const subjects = [...new Set(scheduleData.classes.map((c) => c.subject))].sort(); const teachers = [...new Set(scheduleData.classes.map((c) => c.teacher).filter(Boolean))].sort(); const list = scheduleData.classes.filter((c) => (includeSupport || c.trackable) && (!query || `${c.subject} ${c.teacher} ${c.gradeContext} ${c.block}`.toLowerCase().includes(query.toLowerCase())) && (school === "all" || schoolBand(c) === school) && (subject === "all" || c.subject === subject) && (teacher === "all" || c.teacher === teacher)); return <><div className="eyebrow">Master schedule</div><h1>Every class, accounted for.</h1><div className="filter-grid"><input placeholder="Search subject, teacher, grade..." value={query} onChange={(e) => setQuery(e.target.value)} /><select value={school} onChange={(e) => setSchool(e.target.value)}><option value="all">All school bands</option><option>Middle School</option><option>High School</option></select><select value={subject} onChange={(e) => setSubject(e.target.value)}><option value="all">All subjects</option>{subjects.map((s) => <option key={s}>{s}</option>)}</select><select value={teacher} onChange={(e) => setTeacher(e.target.value)}><option value="all">All teachers</option>{teachers.map((t) => <option key={t}>{t}</option>)}</select><label><input type="checkbox" checked={includeSupport} onChange={(e) => setIncludeSupport(e.target.checked)} /> Include non-teaching rows</label></div><div className="panel table-wrap"><table><thead><tr><th>Class</th><th>Grade</th><th>Teacher</th><th>Block</th><th>Captures</th></tr></thead><tbody>{list.map((c) => <tr key={c.id}><td><strong>{c.subject}</strong></td><td>{gradeLabel(c)}</td><td>{c.teacher || "—"}</td><td>{c.block}</td><td>{countFor(c.id)}/{target}</td></tr>)}</tbody></table></div></>; }
  function coverageView() { const rows = scheduleData.classes.filter((c) => captures.some((x) => x.class_id === c.id)).sort((a, b) => countFor(b.id) - countFor(a.id)); return <><div className="eyebrow">Coverage log</div><h1>Track visits, not photos.</h1><p>No image files are stored.</p><div className="panel table-wrap"><table><thead><tr><th>School</th><th>Grade</th><th>Subject</th><th>Visits</th><th>Dates / remove</th></tr></thead><tbody>{rows.map((c) => <tr key={c.id}><td>{schoolBand(c)}</td><td>{gradeLabel(c)}</td><td>{c.subject}</td><td>{countFor(c.id)}</td><td>{captures.filter((x) => x.class_id === c.id).map((x) => <button className="link-button" key={x.id} disabled={pending} onClick={() => remove(x.id)}>Remove {x.capture_date}</button>)}</td></tr>)}</tbody></table></div></>; }
  const navItems = ["today", "dashboard", "classes", "calendar", "coverage"];
  return <main className="app-frame"><aside><div className="brand">CC <span>ClassCapture</span></div>{navItems.map((item) => <button className={view === item ? "nav active" : "nav"} key={item} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}<div className="aside-note">Secure cloud tracker</div></aside><section className="main"><header><span>Signed in securely</span><form action="/auth/signout" method="post"><button className="link-button">Sign out</button></form></header><div className="page">{view === "today" ? todayView() : view === "dashboard" ? dashboardView() : view === "classes" ? classesView() : view === "coverage" ? coverageView() : <><div className="eyebrow">Rotation calendar</div><h1>Plan the coverage run.</h1><div className="panel calendar-list">{scheduleData.rotations.slice(0, 40).map((r) => <button key={r.date} onClick={() => { setDate(r.date); setView("today"); }}>{r.date} · {r.label}</button>)}</div></>}</div></section><nav className="mobile-nav" aria-label="Mobile navigation">{navItems.map((item) => <button className={view === item ? "active" : ""} key={item} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav></main>;
}
